[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'gina.vim'
"hook_add = 'call config#init#lightline#hook_add()'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'colorscheme onedark'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add='let g:indentLine_color_term =239'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

